
enum ClientControllerState {
    RETURN_TO_MAIN = 0,
    CLIENT_MENU = 1,
    CLIENT_CREATION,
    CLIENT_LISTING,
    CLIENT_SELECTION,
    CLIENT_EDITING,
    CLIENT_EDIT_LIST,
    CLIENT_EDIT_NAME,
    CLIENT_EDIT_PHONE,
    CLIENT_EDIT_CPF,
    CLIENT_EDIT_VIP,
    CLIENT_ADDRESS_MENU,
    CLIENT_ADDRESS_LIST,
    CLIENT_ADDRESS_CREATION,
    CLIENT_ADDRESS_REMOVAL,
    CLIENT_ACCOUNT_MENU,
    CLIENT_ACCOUNT_LIST,
    CLIENT_ACCOUNT_WITHDRAW,
    CLIENT_ACCOUNT_DEPOSIT,
    CLIENT_ACCOUNT_BALANCE,
    CLIENT_ACCOUNT_TRANSFER,
    SHUTDOWN = 999,
    RESET = 1000
}

export default ClientControllerState;