enum ControllerState {
    MAIN_MENU = 0,
    EMPLOYEE_MENU = 1,
    EMPLOYEE_CREATION = 2,
    EMPLOYEE_LISTING = 3,
    EMPLOYEE_SELECTION = 4,
    EMPLOYEE_EDITING = 5,
    EMPLOYEE_EDIT_NAME = 6,
    EMPLOYEE_EDIT_PHONE = 7,
    CLIENT_MENU = 8,
    CLIENT_CREATION = 9,
    CLIENT_LISTING = 10,
    SHUTDOWN = 999,
    RESET = 1000
}

export default ControllerState;